package com.saas.springbackend.payment.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class VerifyPaymentRequestDto {

    // Razorpay orderID
    @NotBlank(message = "Razorpay order ID is required")
    private String razorpayOrderId;

    // Payment Id generated by Razorpay
    @NotBlank(message = "Razorpay payment ID is required")
    private String razorpayPaymentId;

    // Signature returned by Razorpay
    @NotBlank(message = "Razorpay signature is required")
    private String razorpaySignature;
}
